import React from 'react'

function Policy() {
    return (
        <div>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias temporibus odit est recusandae ea eligendi! Aut a odio cumque minus, voluptatibus natus eligendi blanditiis aspernatur excepturi ut praesentium error, qui nostrum cum officia sequi, eius officiis temporibus est quae similique provident ullam neque repellendus. Dignissimos maiores voluptate ullam porro nostrum asperiores ea! Dignissimos ipsum minus commodi facilis voluptatem optio vel aspernatur inventore vero omnis! Voluptas, temporibus mollitia eveniet molestiae iure et quaerat! Sed enim tempore non quos distinctio! Animi sapiente fugiat amet est! Commodi corrupti facilis repudiandae numquam porro molestias sunt totam eos officia sapiente, soluta eaque praesentium quas nobis dignissimos optio provident, libero culpa laboriosam. Doloremque nisi atque eos quia laudantium ab similique minus nulla! Rerum possimus aliquam nisi in, sapiente vero doloribus molestias facilis quasi et incidunt fugit inventore corporis hic delectus unde odit obcaecati libero exercitationem asperiores impedit eligendi! Ipsum atque ullam sed distinctio laudantium voluptates, inventore, laborum sequi vitae alias cupiditate, repellendus ratione maiores laboriosam! Officiis laborum aut ipsam facilis quia similique, natus harum dolores esse quaerat quidem sunt possimus velit ex repellat ea consequatur perspiciatis quam voluptatum praesentium quos. Aperiam corporis mollitia asperiores voluptates tenetur repellendus consequuntur nihil magnam enim ullam esse excepturi explicabo, error dolor nam provident, culpa et, ratione exercitationem qui voluptate aut neque. Aperiam facilis soluta nihil necessitatibus dolorum! Veniam optio nesciunt magnam dignissimos, dolor dolore ex, ipsa rem, architecto deserunt repellat accusamus nemo. Eaque culpa corrupti laboriosam adipisci non, sapiente minima dignissimos sint voluptatibus quae distinctio. Exercitationem maxime aliquam, enim, error neque provident ratione quasi quibusdam totam rerum sunt in! Velit asperiores maxime fuga veritatis. Laudantium dolore asperiores, sequi eligendi nostrum voluptatem optio exercitationem perferendis aliquam non ullam quae unde et quia totam blanditiis deserunt vero incidunt debitis quidem voluptate alias eius? Libero molestias ipsam velit doloremque id pariatur, esse aliquid!
        </div>
    )
}

export default Policy
